[package]
name = "chasedow"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.13"
macroquad-platformer = "0.2.0"
rand = "0.8.5"
futures = "0.3.31"
getrandom = { version = "0.2", features = ["js"] }